POST {{BASE_URL_REST}}/dpm/v1/warehouse/product-inventory/assign
Authorization: Bearer {{TOKEN_REST_STOREKEEPER}} 

{
  "warehouseId": "08c3ae7a-7873-4d0a-a949-489348efa757",
  "productCode": "306872039975",
  "shelfCode": "B-K1-T1-O2"
}
