POST {{BASE_URL_REST}}/dpm/v1/warehouse/product-inventory/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWY2ZGM0LTEwNWQtNzU1Yy05Y2YyLTVhOGMxZmEwMGM4ZiIsImZpcnN0TmFtZSI6Ik5ndXllbiBEdWMgQW5oIiwibGFzdE5hbWUiOm51bGwsImVtYWlsIjoiMjEwMTI0NzNAc3QucGhlbmlrYWEtdW5pLmVkdS52biIsInByb2ZpbGVQaWN0dXJlIjpudWxsLCJwbGFuIjowLCJtcCI6LTEsIm51bURheURlbGV0ZVZpZGVvIjoyMCwic3RvcmVJZCI6IjAxOWY2ZGM0LTEwY2YtNzU1Yy05Y2YyLTYyZWRiOThiNzZkYyIsIm93bmVyU3RvcmUiOiIwMTlmNmRjNC0xMDVkLTc1NWMtOWNmMi01YThjMWZhMDBjOGYiLCJyb2xlcyI6WyJvd25lciIsIndhcmVob3VzZV9zdG9ja2VyIiwic3RvcmVrZWVwZXIiXSwibHMiOjUxMiwib3duZXJPcmciOiJmYTU5ZjZiNy00ODg0LTQwZDktYmMxNy1iNzdjZGIyZTE2MzMiLCJyZWZlcnJhbEJ5IjoiMmM0YzIxZDEtZmZlYy00YzNkLWExNGYtMzk5MGY2OGJhNmE2Iiwic2lkIjoiMDFhMDBlZTUtNDBkNy03ODg0LTgyZWUtNjMzMTQ2NGQ2ZTNjIiwianRpIjoiMDFhMDBlZTUtNDBkNy03ODg0LTgyZWUtNjlhNWUxMzk1YzYwIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzg2OTU2MzAwLCJleHAiOjE3ODcwNDI3MDAsImlzcyI6ImRobl9hcGkifQ.EZ7IYxZMSsDAN6p8j0kRvUbzci_KHZLURW9KeZBuaU0 
{
  "productCode": "NNYRSNFYYT",
  "shelfCode": "A-K1-T3-O3"
}


