POST {{BASE_URL_REST}}/dpm/v1/warehouse/product-inventory/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWY2ZGM0LTEwNWQtNzU1Yy05Y2YyLTVhOGMxZmEwMGM4ZiIsImZpcnN0TmFtZSI6Ik5ndXllbiBEdWMgQW5oIiwibGFzdE5hbWUiOm51bGwsImVtYWlsIjoiMjEwMTI0NzNAc3QucGhlbmlrYWEtdW5pLmVkdS52biIsInByb2ZpbGVQaWN0dXJlIjpudWxsLCJwbGFuIjowLCJtcCI6LTEsIm51bURheURlbGV0ZVZpZGVvIjoyMCwic3RvcmVJZCI6IjAxOWY2ZGM0LTEwY2YtNzU1Yy05Y2YyLTYyZWRiOThiNzZkYyIsIm93bmVyU3RvcmUiOiIwMTlmNmRjNC0xMDVkLTc1NWMtOWNmMi01YThjMWZhMDBjOGYiLCJyb2xlcyI6WyJvd25lciJdLCJscyI6NTEyLCJvd25lck9yZyI6ImZhNTlmNmI3LTQ4ODQtNDBkOS1iYzE3LWI3N2NkYjJlMTYzMyIsInJlZmVycmFsQnkiOiIyYzRjMjFkMS1mZmVjLTRjM2QtYTE0Zi0zOTkwZjY4YmE2YTYiLCJzaWQiOiIwMTlmYWNhOS0yMDZmLTc3NzMtYTdiMS03ZGZiMjVlZDU2NmEiLCJqdGkiOiIwMTlmYWNhOS0yMDZmLTc3NzMtYTdiMS04MjcwYWNkMjkxMDUiLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODUzMDgxOTIsImV4cCI6MTc4NTM5NDU5MiwiaXNzIjoiZGhuX2FwaSJ9.4iXUwbJrAVIVZ8WbIabMdVw7-2ldYIvFBcBJAzJmc6s 

{
  "productCode": "306872039975",
  "shelfCode": "B-K1-T1-O2"
}
