POST {{BASE_URL_REST}}/dpm/v1/warehouse/orders/assign-picker
Authorization: Bearer {{TOKEN_REST_STOREKEEPER}}

{
  "orderIds": [
    "12d5e723-9012-487d-b01d-f3e7efd6f375"
  ],
  "pickerId": "019f6dd6-b361-799a-b216-2b848a0f8594"
}
