POST {{BASE_URL_REST}}/dpm/v1/warehouse/08c3ae7a-7873-4d0a-a949-489348efa757/tote/scan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWY2ZGQ2LWIzNjEtNzk5YS1iMjE2LTJiODQ4YTBmODU5NCIsImZpcnN0TmFtZSI6Ik5ndXllbiBNaW5oIEFuaCIsImxhc3ROYW1lIjpudWxsLCJlbWFpbCI6ImFuaC5uZ3V5ZW5kdWNAZ21haWwuY29tIiwicHJvZmlsZVBpY3R1cmUiOm51bGwsInBsYW4iOjAsIm1wIjotMSwibnVtRGF5RGVsZXRlVmlkZW8iOjIwLCJzdG9yZUlkIjoiMDE5ZjZkYzQtMTBjZi03NTVjLTljZjItNjJlZGI5OGI3NmRjIiwib3duZXJTdG9yZSI6IjAxOWY2ZGM0LTEwNWQtNzU1Yy05Y2YyLTVhOGMxZmEwMGM4ZiIsInJvbGVzIjpbIndhcmVob3VzZV9waWNrZXIiXSwibHMiOjUxMiwib3duZXJPcmciOiIwMTlmNmRjNC0xMGNmLTc1NWMtOWNmMi02MmVkYjk4Yjc2ZGMiLCJyZWZlcnJhbEJ5IjoiMDE5ZjZkYzQtMTA1ZC03NTVjLTljZjItNWE4YzFmYTAwYzhmIiwic2lkIjoiMDFhMDEzMzItMWU3ZS03ODg0LTgyZjAtNTZhOWIzMWMwM2Q4IiwianRpIjoiMDFhMDEzMzItMWU3ZS03ODg0LTgyZjAtNTg4MzRkYTBkZWU5IiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzg3MDI4NDQ2LCJleHAiOjE3ODcxMTQ4NDYsImlzcyI6ImRobl9hcGkifQ.anaP8N-UEmVehxvbsR4RjNfOOqQmEkBP3mp4N-6ygRU 

{
  "toteCode": "T01A4C5F7E5F5"
}

