POST {{BASE_URL_REST}}/dpm/v1/warehouse/orders/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWY2ZGM0LTEwNWQtNzU1Yy05Y2YyLTVhOGMxZmEwMGM4ZiIsImZpcnN0TmFtZSI6Ik5ndXllbiBEdWMgQW5oIiwibGFzdE5hbWUiOm51bGwsImVtYWlsIjoiMjEwMTI0NzNAc3QucGhlbmlrYWEtdW5pLmVkdS52biIsInByb2ZpbGVQaWN0dXJlIjpudWxsLCJwbGFuIjowLCJtcCI6LTEsIm51bURheURlbGV0ZVZpZGVvIjoyMCwic3RvcmVJZCI6IjAxOWY2ZGM0LTEwY2YtNzU1Yy05Y2YyLTYyZWRiOThiNzZkYyIsIm93bmVyU3RvcmUiOiIwMTlmNmRjNC0xMDVkLTc1NWMtOWNmMi01YThjMWZhMDBjOGYiLCJyb2xlcyI6WyJvd25lciJdLCJscyI6NTEyLCJvd25lck9yZyI6ImZhNTlmNmI3LTQ4ODQtNDBkOS1iYzE3LWI3N2NkYjJlMTYzMyIsInJlZmVycmFsQnkiOiIyYzRjMjFkMS1mZmVjLTRjM2QtYTE0Zi0zOTkwZjY4YmE2YTYiLCJzaWQiOiIwMTlmODdlNC04OTM2LTcxMWEtYmM1Yi1hOWZkMzZlOWQ2ZTMiLCJqdGkiOiIwMTlmODdlNC04OTM2LTcxMWEtYmM1Yi1iMjcyYzY0OGVmNWMiLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3ODQ2OTEzMjksImV4cCI6MTc4NDc3NzcyOSwiaXNzIjoiZGhuX2FwaSJ9.IkGQhrYIXpso47j95LAt_ig1RCHoPsjP2SasgTYX-gQ

{
  "assignments": [
    {
      "targetPickerId": "97dee6d6-99cc-486d-a605-05ec5a5621eb",
      "orderIds": [
        "a374539f-1761-4e89-b04b-9d42ddb93dc8",
        "ef7b6eb7-ed47-48ce-bf88-19a136910b3b"
      ]
    }
  ]
}
