### C:\dhn\test\collection\wh\tiktok-scan\req\2-tote-scan-tiktok.http#1
POST https://dev.dohana.vn/dpm/v1/warehouse/08c3ae7a-7873-4d0a-a949-489348efa757/tote/scan
HTTP/1.1 201 Created

# @_RES (formatted)
{
  "orderId": "5ddeb486-0abe-41b4-9718-f17db0c3d094",
  "status": "PICKING",
  "platform": "tiktok",
  "trackingNumber": "859283751254",
  "sourceOrderId": "579569631497258922"
}
# @_END
